### ISSUE TITLE
schimbarea numelui proiectului in "site-asmi"

### ISSUE THREAD

**Issue by mehanix** [as-mi/site-asmi#1]
toate celelalte site-uri au prefixul "site-", doar asmi si cariere nu.
as propune aceasta uniformizare (probabil am ocd :)) )

**Comment by GabrielMajeri** [comment]
E o idee bună :)) dau eu rename la acesta, și dai tu la Cariere?

**Comment by GabrielMajeri** [comment]
Done

**Comment by mehanix** [comment]
@GabrielMajeri nu cred ca am permisiuni sa fac asta, cel putin nu vad nicaieri tabul de "settings" unde ar trebui sa fie pe repo

**Comment by GabrielMajeri** [comment]
Ups, cred că am stricat vreo permisiune când s-a transferat repo-ul.

L-am redenumit acum și ți-am dat admin, ar trebui să fie OK.
